### ISSUE TITLE
Following community style guidelines

### ISSUE THREAD

**Issue by mgrbyte** [c-anna/PyWormbase#2]
Hi,
Minor issue, you should probably follow [PEP8][1] and use all lower-case/underscrore names for modules and packages.
(e.g wormbase_client vs wormbaseClient)

[1]: https://www.python.org/dev/peps/pep-0008/

**Comment by c-anna** [comment]
This is covered in 0.3.0. I updated module names from `endpointGroups` to `endpoint_groups` and `wormbaseClient` to `wormbase_client`. Names of classes and so on inside the files looked OK. Thanks for pointing this out!
